
db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

#spring.profiles.active: qa

spring:
  mvc:
    format:
      date: iso
      date-time: iso-offset
    view:
      prefix: /jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        batch_size: 50
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: none
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 438102212677-4ert1i43ca2815ecpbgkcphv139ifrg1.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8081/login/oauth2/code/google
            scope: openid,email, profile


  messages:
    basename: messages

logging:
  level:
    root: INFO
    shadow.dev.spring.datatabase.pool.ConnectionPool: info
    org.springframework.jdbc.core: trace
    org.springframework.web: trace
  file:
    name: shadow.log
    path: /
server:
  port: 8081

springdoc:
  swagger-ui:
    oauth:
      client-id: 438102212677-4ert1i43ca2815ecpbgkcphv139ifrg1.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

